project:
  type: website

website:
  title: "Kade Benjamin Nef - Data Science Portfolio"
  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "Data Wrangling"
        file: data_wrangling.qmd
      - text: "Data Visualization"
        file: data_visualization.qmd
      - text: "Machine Learning"
        file: machine_learning.qmd
      - text: "SQL/Database"
        file: sql_database.qmd

  sidebar:
    - title: "Data Wrangling"
      style: "docked"
      background: light
      contents:
        - text: "Overview"
          file: data_wrangling.qmd
        - text: "Project 1"
          file: Data_Wrangling/project1.qmd
        - text: "Project 2"
          file: Data_Wrangling/project2.qmd
    - title: "Data Visualization"
      style: "docked"
      background: light
      contents:
        - text: "Overview"
          file: data_visualization.qmd
        - text: "Project 1"
          file: Data_Visualization/Baseball_Analytics.qmd
        - text: "Project 2"
          file: Data_Visualization/project2.qmd
        - text: "Project 3"
          file: Data_Visualization/project3.qmd
        - title: "Project 4"
          file: Data_Visualization/project4.qmd
        - title: "Project 5"
          file: Data_Visualization/project5.qmd
    - title: "SQL/Database"
      style: "docked"
      background: light
      contents:
        - text: "Overview"
          file: sql_database.qmd
        - text: "Project 1"
          file: SQL_Relational_Database/project1.qmd
        - text: "Project 2"
          file: SQL_Relational_Database/project2.qmd
    - title: "Machine Learning"
      style: "docked"
      background: light
      contents:
        - text: "Overview"
          file: machine_learning.qmd
        - text: "Project 1"
          file: Machine_Learning/project1.qmd
        - text: "Project 2"
          file: Machine_Learning/project2.qmd
        - text: "Project 3"
          file: Machine_Learning/project3.qmd

format:
  html:
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    self-contained: true
    theme: cosmo
    css: styles.css
    title-block-banner: false