---
title: "Resume"
format:
  html:
    toc: false
    theme: cosmo
    css: styles.css
    page-layout: full
    title-block-banner: true
---

::: {.text-center}
# Kade Nef
:::

<div style="text-align: center;">
**Email:** [nefkade2@gmail.com](mailto:nefkade2@gmail.com) | **LinkedIn:** [Profile](https://www.linkedin.com/in/kade-nef/) | **Phone:**(208) 227-4183
</div>

---

## Education

<div style="display: flex; justify-content: space-between; width: 100%;">
  <div><strong>Bachelor of Science in Business Analytics</strong></div>
  <div>Apr. 2026</div>
</div>
<div style="display: flex; justify-content: space-between; width: 100%;">
  <div>Brigham Young University–Idaho</div>
  <div>Rexburg, ID</div>
</div>

- Minor: Finance  
- Certificate: Data Science

---

## Technical Skills

<div><strong>Data Analysis & Visualization</strong></div>
Power BI (Advanced) | Tableau (Intermediate) | Excel (Advanced)

<div style="margin-top: 8px;"><strong>Data Wrangling & Querying</strong></div>
SQL – MySQL, SQLite (Proficient) | R – Tidyverse (Proficient) | Python – Pandas (Intermediate)

<div style="margin-top: 8px;"><strong>Statistical & Predictive Modeling</strong></div>
Statistical Inference, Regression (Proficient) | Scikit-learn – Machine Learning Concepts (Intermediate)

---

## Experience

<div style="display: flex; justify-content: space-between; width: 100%;">
  <div><strong>Teaching Assistant – Business Analytics</strong></div>
  <div>Apr. 2025 – Present | Rexburg, ID</div>
</div>
- Evaluated 100+ Power BI projects, delivering targeted feedback to enhance DAX performance, model accuracy, and actionable insight  
- Reviewed dashboards and data models to assess efficiency, storytelling clarity, and technical execution

<div style="display: flex; justify-content: space-between; width: 100%;">
  <div><strong>Team Lead – Building Bridges</strong></div>
  <div>Jan. 2025 – Apr. 2025 | Rexburg, ID</div>
</div>
- Led a team of 5 interns in developing and piloting a program to deliver Arbinger principles to small local businesses  
- Conducted market research and assisted with pricing strategies to optimize business solutions

<div style="display: flex; justify-content: space-between; width: 100%;">
  <div><strong>Teller – Beehive Federal Credit Union</strong></div>
  <div>Apr. 2024 – Jan. 2025 | Rigby, ID</div>
</div>
- Communicated with members and coworkers to resolve issues and ensure excellent service  
- Processed transactions and maintained records with 100% accuracy

<div style="display: flex; justify-content: space-between; width: 100%;">
  <div><strong>Volunteer Representative – The Church of Jesus Christ of Latter-day Saints</strong></div>
  <div>Sep. 2020 – Sep. 2022 | San Jose, CA / Oaxaca, Mexico</div>
</div>
- Demonstrated leadership skills by helping a team of twenty set and strive to attain goals  
- Devoted 60+ hours a week for two years, planning effectively and adapting when needed  
- Became fluent in Spanish

---

## Awards

**Microsoft Excel – Business Professionals of America Regionals**  
*2019 | Idaho Falls, ID*

---
_Last updated: June 2025_  
_Portfolio: [nefkade.github.io](https://nefkade.github.io)_