---
title: "[Insert Project Title]"
subtitle: "Emphasis on Data Wrangling"
author: "Kade Nef"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(lubridate)
library(DT)

# covid_data <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")
```

The COVID-19 dataset from Our World in Data is widely recognized and regularly updated, but it still presents meaningful opportunities for data wrangling. Working with this global dataset, I applied my skills in R to...

### Transforming the Raw Data

#### Raw

```{r}
# datatable(
#   covid_data %>% sample_n(100),
#   options = list(pageLength = 10),
#   caption = "Sample of Raw COVID-19 Data"
# )
```

#### clean

